DROP DATABASE IF EXISTS `DB`;
CREATE DATABASE `DB`;
USE `DB`;

DROP TABLE IF EXISTS `feedback`;
CREATE TABLE `feedback` (
  `task_id` VARCHAR(255) NOT NULL,
  `response` BOOLEAN NOT NULL,
  `img1` BLOB NOT NULL,
  `img2` BLOB NOT NULL,
  PRIMARY KEY (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
